@neatoBrandId = {{brands.response.body.$[?(@.name=='Neato')].id}}

##################################################
### Get Admin Token
##################################################
# @name getAdminToken
POST https://{{auth0_domain}}/oauth/token
Content-Type: application/json

{
    "grant_type":"password",
    "username":"{{admin_email}}",
    "password":"{{admin_password}}",
    "client_id": "{{auth0_clientId}}",
    "client_secret": "{{auth0_clientSecret}}",
    "audience": "{{auth0_audience}}",
    "scope": "openid profile"
}
###
@adminToken = {{getAdminToken.response.body.id_token}}

##################################################
### Get available brands
##################################################
# @name brands
GET {{api_url}}/brands
Content-Type: application/json
Authorization: Bearer {{adminToken}}

##################################################
### Add tags
##################################################
POST {{api_url}}/brands/{{neatoBrandId}}/tags
Content-Type: application/json
Authorization: Bearer {{adminToken}}

[
    "in-warranty-repair",
    "out-of-warranty-repair",
    "troubleshooting-fixed-issue",
    "customer-unresponsive",
    "general-question",
    "purchase-robot",
    "purchase-part-accessories"
]