##################################################
### Get Admin Token
##################################################
# @name getAdminToken
POST https://{{auth0_domain}}/oauth/token
Content-Type: application/json

{
    "grant_type":"password",
    "username":"{{admin_email}}",
    "password":"{{admin_password}}",
    "client_id": "{{auth0_clientId}}",
    "audience": "{{auth0_audience}}",
    "scope": "openid profile"
}
###
@adminToken = {{getAdminToken.response.body.id_token}}

##################################################
### Get available brands
##################################################
# @name brands
GET {{api_url}}/brands
Content-Type: application/json
Authorization: Bearer {{adminToken}}

###
@brandId = {{brands.response.body.$[?(@.name=='HP')].id}}


##################################################
### Create new super solver accounts
##################################################
# @name createSuperSolvers
POST {{api_url}}/advocates/super-solvers
Content-Type: application/json
Authorization: Bearer {{adminToken}}

[
  {
    "FirstName": "FULCHAND",
    "LastName": "EKKA",
    "Email": "fulchand.ekka@concentrix.com",
    "Password": ""
  },
  {
    "FirstName": "Sweta",
    "LastName": "Goyal",
    "Email": "sweta.goyal@concentrix.com",
    "Password": ""
  },
  {
    "FirstName": "Jaspreet",
    "LastName": "Saini",
    "Email": "jaspreet.saini@concentrix.com",
    "Password": ""
  },
  {
    "FirstName": "Sandeep",
    "LastName": "Singh",
    "Email": "sandeep.singh19@concentrix.com",
    "Password": ""
  },
  {
    "FirstName": "Atul",
    "LastName": "Kumar",
    "Email": "atul.kumar6@concentrix.com",
    "Password": ""
  },
  {
    "FirstName": "Imran",
    "LastName": "I",
    "Email": "imran.i1@concentrix.com",
    "Password": ""
  },
  {
    "FirstName": "Anoop",
    "LastName": "Singh",
    "Email": "anoop.singh2@concentrix.com",
    "Password": ""
  },
  {
    "FirstName": "Chandra",
    "LastName": "Shekhar",
    "Email": "chandra.shekhar@concentrix.com",
    "Password": ""
  },
  {
    "FirstName": "Abid",
    "LastName": "Khan",
    "Email": "abid.khan3@concentrix.com",
    "Password": ""
  }
]


###
@advocateId = 123-guid-here

##################################################
### Assign brands to super solvers
##################################################
POST {{api_url}}/advocates/{{advocateId}}/brands?authorised=true
Content-Type: application/json
Authorization: Bearer {{adminToken}}

[
	"{{brandId}}"
]
