##################################################
### Get Admin Token
##################################################
# @name getAdminToken
POST https://{{auth0_domain}}/oauth/token
Content-Type: application/json

{
    "grant_type":"password",
    "username":"{{admin_email}}",
    "password":"{{admin_password}}",
    "client_id": "{{auth0_clientId}}",
    "audience": "{{auth0_audience}}",
    "scope": "openid profile"
}
###
@adminToken = {{getAdminToken.response.body.id_token}}

##################################################
### Create new brand
##################################################
# @name createBrand
POST {{api_url}}/brands
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
	"Name": "HP Americas",
	"Code": "AMERICAS",
	"ShortCode": "AMS",
	"Thumbnail": "https://assets.solvnow.com/hp-ams/HP.png",
	"Logo": "https://assets.solvnow.com/hp-ams/HP.png",
	"ContractUrl": "https://assets.solvnow.com/hp-ams/contract.txt",
	"ContractInternalUrl": "https://assets.solvnow.com/hp-ams/contract.txt",
	"CreateTicketSubheader": "Chat Support is available 24/7",
	"AdvocateTitle": "SUPPORT SPECIALIST",
	"FeePercentage": 0.3,
	"TicketPrice": 0.0,
	"VatRate": 0.0000,
	"PaymentRouteId": 2,
	"InductionDoneMessage": "## CONGRATULATIONS! \n\n You have successfully viewed the HP 101 guidelines. To represent HP, you'll now need to take a peer knowledge check.",
	"InductionInstructions": "HP has put together this 101 guide to get you authorised to Solv for them. \n\n **NOTE: You must not copy, share or duplicate any of the contents of this section!** \n\n HP is a global leader in home computing, you will be helping users of their products with out of warranty support, so it will be technical in nature on hardware, software and networking type questions. \n\n Support will be 24/7 but we think busiest from Monday to Friday, lighter over the weekend. We expect to see anything from 2000-3000 customers per month to start and grow. \n\n You will earn around $0.80 per chat ticket which will take between 3-10 mins of time to complete.",
	"AutomaticAuthorization": true,
	"UnauthorizedMessage": null,
	"AgreementContent": null,
	"AgreementHeading": null,
	"IsAgreementRequired": false,
	"InvoicingEnabled": true,
	"InvoicingDashboardEnabled": true,
	"WaitMinutesToClose": 4320,
	"Color": "#4294D1",
	"NpsEnabled": 1,
	"TagsEnabled": 1,
	"TicketsExportEnabled": 1,
	"SuperSolversEnabled": 1,
	"PushBackToClientEnabled": 1,
	"SposEnabled": 1,
	"TicketsImportEnabled": 1,
	"SposEmail": "solvhpams-sit@mailinator.com"
}

@brandId = {{createBrand.response.body.id}}

##################################################
### Create induction section for brand
##################################################
POST {{api_url}}/brands/{{brandId}}/induction/sections
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
	"Sections": [
		{
			"Id": "4e01fb9e-ae76-4e6c-8efc-f1f6b3ffed1e",
			"Name": "Product knowledge",
			"Order": 1,
			"Items": [
				{
					"Id": "589ce755-0677-4ca1-8c8c-79fe5b380d2e",
					"Name": "Solv flow",
					"Order": 1,
					"Source": "https://assets.solvnow.com/hp/solv-flow.html"
				}
			]
		}
	]
}

##################################################
### Create new client accounts
##################################################
# @name createClients
POST {{api_url}}/brands/{{brandId}}/clients
Content-Type: application/json
Authorization: Bearer {{adminToken}}

[
	{
		"Email": "solv+hpams@tigerspike.com",
		"FirstName": "Client",
		"LastName": "HP-AMS",
		"Password": "@123QWEasdzxc"
	}
]


##################################################
### TEST ENVIRONMENTS ONLY: Create defined (simplified) key for brand
##################################################
PUT {{api_url}}/brands/{{brandId}}/api-key
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
	"m2m": "hp-ams-1",
	"sdk": "hp-ams-1"
}

##################################################
### Create quiz
##################################################
POST {{api_url}}/brands/{{brandId}}/quiz
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
	"Title": "Final Evaluation Assessment",
	"Description": "You have successfully viewed the HP 101 guidelines. To represent HP, you'll now need to take a peer knowledge check. There are 30 questions but don’t worry, you still pass if you get four questions wrong.",
	"AllowedMistakes": 0,
	"FailureMessage": "To Solv for HP you're going to need pass the assessment.Hit the button below to brush up on your brand knowledge or try the quiz again.",
	"SuccessMessage": "You're now fully authorised with HP, so go ahead, pick up your first ticket and start earning right now.",
	"Questions": [
		{
			"Title": "What brands are you solving for?",
			"IsMultiChoice": false,
			"Options": [
				{
					"Text": "HP",
					"Correct": true
				},
				{
					"Text": "Samsung",
					"Correct": false
				},
				{
					"Text": "DELL",
					"Correct": false
				}
			]
		}
	]
}

##################################################
### Add new whitelist
##################################################
POST {{api_url}}/brands/{{brandId}}/whitelist
Content-Type: application/json
Authorization: Bearer {{adminToken}}

[
	"https://store.hp.com/in-en/default/installation",
	"18001084747",
	"escalation@redeemnow.in",
	"https://hp.care/diagnostic-tools",
	"http://www.hp.com/go/privacy",
	"http://www.hp.com/go/hpcarepack/register",
	"https://store.hp.com/in-en/default/sales/guest/form",
	"https://hp.care/virtualagent-printer",
	"http://www.register.hp.com",
	"desktop@redeemnow.in",
	"https://hp.care/virtualagent-pc",
	"18001084746",
	"18002587170",
	"https://support.hp.com/in-en",
	"https://support.hp.com/in-en/checkwarranty"
]

##################################################
### Add abandon reasons
##################################################
POST {{api_url}}/brands/{{brandId}}/abandon-reasons
Content-Type: application/json
Authorization: Bearer {{adminToken}}

[
	{ "Name": "Customer has an existing query/case", "Action": "Escalate" },
	{ "Name": "Unhappy customer/Complaint", "Action": "Escalate" },
	{ "Name": "Warranty dispute", "Action": "Escalate" },
	{ "Name": "I don't have the skills/knowledge to resolve" },
	{ "Name": "CXRequestedL2Support", "Action": "Escalate" }
]

##################################################
### Add tags
##################################################
POST {{api_url}}/brands/{{brandId}}/tags
Content-Type: application/json
Authorization: Bearer {{adminToken}}

[
	{ "Name": "hardware", "Action": "Escalate" },
	{ "Name": "software" },
	{ "Name": "upsell-only", "Action": "Escalate" }
]


##################################################
### PRODUCTION ONLY REQUESTS -----------------------------------------------------
##################################################

##################################################
### Create production new client accounts
##################################################
# @name createClients
POST {{api_url}}/brands/{{brandId}}/clients
Content-Type: application/json
Authorization: Bearer {{adminToken}}

[
	{
		"Email": "holly.steele-nicholson+hpams@concentrix.com",
		"FirstName": "Client",
		"LastName": "HP-AMS",
		"Password": "set-password-here"
	}	
]

##################################################
### Create unique api keys for brand
##################################################
# @name generateApiKey
POST {{api_url}}/brands/{{brandId}}/api-key
Content-Type: application/json
Authorization: Bearer {{adminToken}}

@sdkApiKey = {{generateApiKey.response.body.sdk}}