namespace Tigerspike.Solv.Services.WebHook.Enums
{
	/// <summary>
	/// Types of message
	/// </summary>
	public enum MessageType
	{
		/// <summary>
		/// Type of message that is entered by a user.
		/// </summary>
		Message = 1,

		/// <summary>
		/// Type of message that is generated by the system.
		/// </summary>
		SystemMessage = 2,

		///<summary>
		/// Type of message that represents a status change
		/// </summary>
		StatusChange = 3,

		/// <summary>
		/// Type of message that represents a file that has been successfully uploaded.
		/// </summary>
		Attachment = 4,

		///<summary>
		/// Type of message that represents an action
		/// </summary>
		Action = 5,
	}
}
