version: "3.5"
services:
  solv.mysql:
    image: mysql:5.7
    container_name: solv.mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: T!g3rsp!k3
      MYSQL_USER: solv.api
      MYSQL_PASSWORD: Billions123
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS solv; CREATE DATABASE IF NOT EXISTS `solv.invoicing`; GRANT ALL ON *.* TO `solv.api`;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1" 
    networks:
      - solv

  solv.redis:
    image: redis:latest
    container_name: solv.redis
    ports:
      - "6379:6379"
    networks:
      - solv

  solv.quartz:
    image: masstransit/quartz:7.1.5
    ports:
      - "5002:80"
    environment:
      MT_TRANSPORT: 'SQS'
      MT_SQS__REGION: ''
      MT_Scheduler: 'local-quartz-sqs'
      MT_Quartz__InstanceName: 'MassTransit-Quartz'
      MT_Quartz__Queue: 'local-quartz-sqs'
      MT_Quartz__ConnectionString: 'Server=solv.mysql;Port=3306;Database=solv;Uid=solv.api;Pwd=Billions123;UseAffectedRows=True;TreatTinyAsBoolean=True'
      MT_Quartz__Provider: 'MySql'
      MT_Quartz__DriverDelegateType: 'Quartz.Impl.AdoJobStore.MySQLDelegate, Quartz'
    networks:
      - solv
    logging:
      driver: none
    depends_on:
      - solv.mysql
      - localstack

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: solv.redisinsight
    restart: always
    ports:
      - "8081:8081"
      - "8001:8001"
    networks:
      - solv

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: solv.elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    networks:
      - solv

  logstash:
    image: docker.elastic.co/logstash/logstash:6.7.0
    container_name: solv.logstash
    depends_on:
      - elasticsearch
    ports:
      - 12201:12201/udp
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - solv

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    container_name: solv.kibana
    depends_on:
      - logstash
    ports:
      - 5601:5601
    networks:
      - solv

  solv.dynamodb:
    image: amazon/dynamodb-local
    container_name: solv.dynamodb
    entrypoint: java
    command: "-jar DynamoDBLocal.jar -sharedDb"
    restart: always
    ports:
      - "8000:8000"
    networks:
      - solv

  localstack:
    image: localstack/localstack:0.10.9
    container_name: solv.localstack
    ports:
      - "4575:4575"
      - "4576:4576"
      - "8080:8080"
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=eu-west-1
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - HOSTNAME=localhost
      - HOSTNAME_EXTERNAL=localhost
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER="${TMPDIR:-/tmp}/localstack"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /tmp/localstack:exec,mode=600
    networks:
      solv:
        aliases:
          - docker.localhost

networks:
  solv:
    name: solv
    driver: bridge
