// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tigerspike.Solv.Infra.Data.Context;

namespace Tigerspike.Solv.Infra.Data.Migrations
{
    [DbContext(typeof(SolvDbContext))]
    [Migration("20200915062405_DCTXS2-2087")]
    partial class DCTXS22087
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.AbandonReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBlockedAdvocate")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsForcedEscalation")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("BrandId", "Name")
                        .IsUnique();

                    b.ToTable("AbandonReason");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Advocate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Csat")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("IdentityApplicantId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("IdentityCheckId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("IdentityCheckResultUrl")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<int>("IdentityVerificationStatus")
                        .HasColumnType("int");

                    b.Property<bool>("InternalAgent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PaymentAccountId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<bool>("PaymentEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PaymentMethodSetup")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PracticeComplete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Practicing")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowBrandNotification")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Source")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Super")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("VideoWatched")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Advocate");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.AdvocateApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("ApplicationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("CompletedEmailSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletionHash")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<bool>("InternalAgent")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("InvitationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("InvitationEmailSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("Phone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30)
                        .HasDefaultValue(null);

                    b.Property<bool>("ProfilingEmailSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ResponseEmailSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Source")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("State")
                        .HasColumnType("varchar(2) CHARACTER SET utf8mb4")
                        .HasMaxLength(2);

                    b.Property<string>("Token")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("AdvocateApplication");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.AdvocateApplicationBrand", b =>
                {
                    b.Property<Guid>("AdvocateApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.HasKey("AdvocateApplicationId", "BrandId");

                    b.HasIndex("BrandId");

                    b.ToTable("AdvocateApplicationBrand");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.AdvocateBrand", b =>
                {
                    b.Property<Guid>("AdvocateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("AgreementAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Authorized")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ContractAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Csat")
                        .HasColumnType("decimal(3,2)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Inducted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AdvocateId", "BrandId");

                    b.HasIndex("BrandId");

                    b.ToTable("AdvocateBrand");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.AdvocateInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AdvocateId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("InvoicingCycleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PaymentFailureDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PlatformBillingDetailsId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdvocateId");

                    b.HasIndex("InvoicingCycleId");

                    b.HasIndex("PlatformBillingDetailsId");

                    b.HasIndex("AdvocateId", "ReferenceNumber")
                        .IsUnique();

                    b.HasIndex("AdvocateId", "Sequence")
                        .IsUnique();

                    b.ToTable("AdvocateInvoice");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.AdvocateInvoiceLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AdvocateInvoiceId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TicketsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdvocateInvoiceId");

                    b.HasIndex("BrandId");

                    b.ToTable("AdvocateInvoiceLineItem");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("varchar(36) CHARACTER SET utf8mb4")
                        .HasMaxLength(36);

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(36) CHARACTER SET utf8mb4")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("BrandId");

                    b.HasIndex("UserId");

                    b.ToTable("ApiKey");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.BillingDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CompanyNumber")
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<bool>("IsPlatformOwner")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("VatNumber")
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("BillingDetails");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdvocateTitle")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AgreementContent")
                        .HasColumnType("longtext");

                    b.Property<string>("AgreementHeading")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<bool>("AutomaticAuthorization")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BillingAgreementId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BillingAgreementToken")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("BillingDetailsId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .HasColumnType("varchar(7) CHARACTER SET utf8mb4")
                        .HasMaxLength(7);

                    b.Property<string>("ContractInternalUrl")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("ContractUrl")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("CreateTicketInstructions")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CreateTicketSubheader")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("FeePercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(6,4)")
                        .HasDefaultValue(0.3m);

                    b.Property<string>("InductionDoneMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("InductionInstructions")
                        .HasColumnType("longtext");

                    b.Property<bool>("InvoicingDashboardEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("InvoicingEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAgreementRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPractice")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Logo")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<bool>("NpsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PaymentAccountId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("PaymentRouteId")
                        .HasColumnType("int");

                    b.Property<bool>("PushBackToClientEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("QuizId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("SuperSolversEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TagsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<decimal>("TicketPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(3m);

                    b.Property<bool>("TicketsExportEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UnauthorizedMessage")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("VatRate")
                        .HasColumnType("decimal(6,4)");

                    b.Property<int>("WaitMinutesToClose")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4320);

                    b.HasKey("Id");

                    b.HasIndex("BillingDetailsId");

                    b.HasIndex("PaymentRouteId");

                    b.HasIndex("QuizId")
                        .IsUnique();

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.BrandAdvocateResponseConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<sbyte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("BrandAdvocateResponseConfig");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.BrandFormField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Options")
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("Validation")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.ToTable("BrandFormField");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.BrandFormFieldType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BrandFormFieldType");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.BrandNotificationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .HasColumnType("longtext");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<int>("DeliverAfterSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Header")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<sbyte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("BrandNotificationConfig");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.BrandTicketPriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(15,2)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("UserId");

                    b.ToTable("BrandTicketPriceHistory");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.ClientInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(15,2)");

                    b.Property<Guid>("BrandBillingDetailsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("InvoiceTotal")
                        .HasColumnType("decimal(15,2)");

                    b.Property<Guid>("InvoicingCycleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PaymentFailureDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PaymentTotal")
                        .HasColumnType("decimal(15,2)");

                    b.Property<Guid>("PlatformBillingDetailsId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("TicketsCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("VatAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("VatRate")
                        .HasColumnType("decimal(6,4)");

                    b.HasKey("Id");

                    b.HasIndex("BrandBillingDetailsId");

                    b.HasIndex("BrandId");

                    b.HasIndex("InvoicingCycleId");

                    b.HasIndex("PlatformBillingDetailsId");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.ToTable("ClientInvoice");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Induction.AdvocateSectionItem", b =>
                {
                    b.Property<Guid>("AdvocateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SectionItemId")
                        .HasColumnType("char(36)");

                    b.HasKey("AdvocateId", "SectionItemId");

                    b.HasIndex("SectionItemId");

                    b.ToTable("InductionAdvocateSectionItem");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Induction.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("InductionSection");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Induction.SectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<Guid>("SectionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("InductionSectionItem");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.InvoicingCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasAlternateKey("From");

                    b.HasAlternateKey("To");

                    b.ToTable("InvoicingCycle");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AdvocateInvoiceLineItemId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<Guid?>("ClientInvoiceId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasAlternateKey("ReferenceNumber");

                    b.HasIndex("AdvocateInvoiceLineItemId")
                        .IsUnique();

                    b.HasIndex("ClientInvoiceId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.PaymentRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("PaymentRoute");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationAnswerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("QuestionOptionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StaticAnswer")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationAnswerId");

                    b.HasIndex("QuestionOptionId");

                    b.ToTable("ProfileAnswer");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.ApplicationAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AdvocateApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AdvocateApplicationId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ProfileApplicationAnswer");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(300) CHARACTER SET utf8mb4")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("ProfileArea");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.ProfileBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BrandName")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("ProfileBrands");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Optional")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("varchar(300) CHARACTER SET utf8mb4")
                        .HasMaxLength(300);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(300) CHARACTER SET utf8mb4")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("ProfileQuestion");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.QuestionDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuestionOptionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionOptionId");

                    b.ToTable("ProfileQuestionDependency");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Optional")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubText")
                        .IsRequired()
                        .HasColumnType("varchar(300) CHARACTER SET utf8mb4")
                        .HasMaxLength(300);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("varchar(300) CHARACTER SET utf8mb4")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("ProfileQuestionOption");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.QuestionOptionDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuestionOptionDependencyTargetId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuestionOptionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionOptionId");

                    b.ToTable("ProfileQuestionOptionDependency");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.QuestionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsAllRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMultiChoice")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSlider")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(300) CHARACTER SET utf8mb4")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("ProfileQuestionType");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("AllowedMistakes")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(300) CHARACTER SET utf8mb4")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("Quiz");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMultiChoice")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(300) CHARACTER SET utf8mb4")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestion");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.QuizQuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Correct")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuizQuestionOption");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.RejectionReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("RejectionReason");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Sequence", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Sequence");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("Action")
                        .HasColumnType("int");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("BrandId", "Name")
                        .IsUnique();

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<sbyte>("AbandonedCount")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("AdvocateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AdvocateInvoiceId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ChaserEmails")
                        .HasColumnType("int");

                    b.Property<Guid?>("ClientInvoiceId")
                        .HasColumnType("char(36)");

                    b.Property<sbyte?>("ClosedBy")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<sbyte?>("Complexity")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("CorrectlyDiagnosed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<sbyte?>("Csat")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CsatDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EscalatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("EscalatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EscalationReason")
                        .HasColumnType("int");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime?>("FirstAssignedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FirstMessageDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPractice")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastAdvocateMessageDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastCustomerMessageDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<sbyte?>("Nps")
                        .HasColumnType("tinyint");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("ReferenceId")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<sbyte>("RejectionCount")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ReservationExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SuperSolverFirstMessageDate")
                        .HasColumnType("datetime(6)");

                    b.Property<sbyte>("TransportType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AdvocateId");

                    b.HasIndex("AdvocateInvoiceId");

                    b.HasIndex("BrandId");

                    b.HasIndex("ClientInvoiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EscalatedById");

                    b.HasIndex("Number");

                    b.HasIndex("Question");

                    b.HasIndex("SourceId");

                    b.HasIndex("Status");

                    b.HasIndex("BrandId", "ReferenceId")
                        .IsUnique();

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketAbandonHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketAbandonHistory");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketAbandonReason", b =>
                {
                    b.Property<Guid>("TicketAbandonHistoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AbandonReasonId")
                        .HasColumnType("char(36)");

                    b.HasKey("TicketAbandonHistoryId", "AbandonReasonId");

                    b.HasIndex("AbandonReasonId");

                    b.ToTable("TicketAbandonReason");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketEscalationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int?>("AbandonedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomerMessage")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("OpenTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("RejectionCount")
                        .HasColumnType("int");

                    b.Property<int?>("TicketSourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketSourceId");

                    b.HasIndex("BrandId", "TicketSourceId")
                        .IsUnique();

                    b.ToTable("TicketEscalationConfig");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketMetadataItem", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("TicketId", "Key");

                    b.ToTable("TicketMetadataItem");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketRejectionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketRejectionHistory");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketRejectionReason", b =>
                {
                    b.Property<Guid>("TicketRejectionHistoryId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RejectionReasonId")
                        .HasColumnType("int");

                    b.HasKey("TicketRejectionHistoryId", "RejectionReasonId");

                    b.HasIndex("RejectionReasonId");

                    b.ToTable("TicketRejectionReason");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TicketSource");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AdvocateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AdvocateId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketStatusHistory");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("char(36)");

                    b.HasKey("TagId", "TicketId");

                    b.HasIndex("TagId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketTag");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AlternateEmail")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Country")
                        .HasColumnType("varchar(5) CHARACTER SET utf8mb4")
                        .HasMaxLength(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.Property<string>("State")
                        .HasColumnType("varchar(2) CHARACTER SET utf8mb4")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");

                    b.HasIndex("AlternateEmail")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.WebHook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Authorization")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Secret")
                        .HasColumnType("varchar(36) CHARACTER SET utf8mb4")
                        .HasMaxLength(36);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<int>("WebHookEvent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("UserId");

                    b.ToTable("WebHook");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.AbandonReason", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", null)
                        .WithMany("AbandonReasons")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Advocate", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.AdvocateApplicationBrand", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.AdvocateApplication", "AdvocateApplication")
                        .WithMany("BrandAssignments")
                        .HasForeignKey("AdvocateApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", "Brand")
                        .WithMany("AdvocateApplications")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.AdvocateBrand", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Advocate", null)
                        .WithMany("Brands")
                        .HasForeignKey("AdvocateId")
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("AdvocateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", "Brand")
                        .WithMany("Advocates")
                        .HasForeignKey("BrandId")
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.AdvocateInvoice", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Advocate", "Advocate")
                        .WithMany()
                        .HasForeignKey("AdvocateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.InvoicingCycle", "InvoicingCycle")
                        .WithMany()
                        .HasForeignKey("InvoicingCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.BillingDetails", "PlatformBillingDetails")
                        .WithMany()
                        .HasForeignKey("PlatformBillingDetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.AdvocateInvoiceLineItem", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.AdvocateInvoice", "AdvocateInvoice")
                        .WithMany("LineItems")
                        .HasForeignKey("AdvocateInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.ApiKey", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Brand", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.BillingDetails", null)
                        .WithMany()
                        .HasForeignKey("BillingDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.PaymentRoute", "PaymentRoute")
                        .WithMany()
                        .HasForeignKey("PaymentRouteId");

                    b.HasOne("Tigerspike.Solv.Domain.Models.Quiz", null)
                        .WithOne("Brand")
                        .HasForeignKey("Tigerspike.Solv.Domain.Models.Brand", "QuizId");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.BrandAdvocateResponseConfig", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", null)
                        .WithMany("ResponseConfig")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.BrandFormField", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", "Brand")
                        .WithMany("FormFields")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.BrandFormFieldType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.BrandNotificationConfig", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", "Brand")
                        .WithMany("NotificationConfig")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.BrandTicketPriceHistory", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Client", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.ClientInvoice", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.BillingDetails", "BrandBillingDetails")
                        .WithMany()
                        .HasForeignKey("BrandBillingDetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.InvoicingCycle", "InvoicingCycle")
                        .WithMany()
                        .HasForeignKey("InvoicingCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.BillingDetails", "PlatformBillingDetails")
                        .WithMany()
                        .HasForeignKey("PlatformBillingDetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Induction.AdvocateSectionItem", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Advocate", "Advocate")
                        .WithMany("AdvocateSectionItems")
                        .HasForeignKey("AdvocateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.Induction.SectionItem", "SectionItem")
                        .WithMany("AdvocateSectionItems")
                        .HasForeignKey("SectionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Induction.Section", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", "Brand")
                        .WithMany("InductionSections")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Induction.SectionItem", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Induction.Section", "Section")
                        .WithMany("SectionItems")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Payment", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.AdvocateInvoiceLineItem", "AdvocateInvoiceLineItem")
                        .WithOne("Payment")
                        .HasForeignKey("Tigerspike.Solv.Domain.Models.Payment", "AdvocateInvoiceLineItemId");

                    b.HasOne("Tigerspike.Solv.Domain.Models.ClientInvoice", null)
                        .WithMany()
                        .HasForeignKey("ClientInvoiceId");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.Answer", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Profile.ApplicationAnswer", "ApplicationAnswer")
                        .WithMany("Answers")
                        .HasForeignKey("ApplicationAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.Profile.QuestionOption", "QuestionOption")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionOptionId");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.ApplicationAnswer", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.AdvocateApplication", "AdvocateApplication")
                        .WithMany("ApplicationAnswers")
                        .HasForeignKey("AdvocateApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.Profile.Question", "Question")
                        .WithMany("ApplicationAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.Question", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Profile.Area", "Area")
                        .WithMany("Questions")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.Profile.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.QuestionDependency", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Profile.Question", "Question")
                        .WithMany("QuestionDependencies")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.Profile.QuestionOption", "QuestionOption")
                        .WithMany("QuestionDependencies")
                        .HasForeignKey("QuestionOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.QuestionOption", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Profile.Question", "Question")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Profile.QuestionOptionDependency", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Profile.QuestionOption", "QuestionOption")
                        .WithMany("QuestionOptionDependencies")
                        .HasForeignKey("QuestionOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.QuizQuestion", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Quiz", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.QuizQuestionOption", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.QuizQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Tag", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", null)
                        .WithMany("Tags")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.Ticket", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Advocate", "Advocate")
                        .WithMany()
                        .HasForeignKey("AdvocateId");

                    b.HasOne("Tigerspike.Solv.Domain.Models.AdvocateInvoice", null)
                        .WithMany("Tickets")
                        .HasForeignKey("AdvocateInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.ClientInvoice", null)
                        .WithMany("Tickets")
                        .HasForeignKey("ClientInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tigerspike.Solv.Domain.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.Advocate", "EscalatedSolver")
                        .WithMany()
                        .HasForeignKey("EscalatedById");

                    b.HasOne("Tigerspike.Solv.Domain.Models.TicketSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketAbandonHistory", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Ticket", null)
                        .WithMany("AbandonHistory")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketAbandonReason", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.AbandonReason", "AbandonReason")
                        .WithMany()
                        .HasForeignKey("AbandonReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.TicketAbandonHistory", null)
                        .WithMany("Reasons")
                        .HasForeignKey("TicketAbandonHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketEscalationConfig", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", null)
                        .WithMany("TicketEscalationConfigs")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.TicketSource", null)
                        .WithMany()
                        .HasForeignKey("TicketSourceId");
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketMetadataItem", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Ticket", null)
                        .WithMany("Metadata")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketRejectionHistory", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Ticket", null)
                        .WithMany("RejectionHistory")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketRejectionReason", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.RejectionReason", "RejectionReason")
                        .WithMany()
                        .HasForeignKey("RejectionReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.TicketRejectionHistory", null)
                        .WithMany("Reasons")
                        .HasForeignKey("TicketRejectionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketStatusHistory", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Advocate", "Advocate")
                        .WithMany()
                        .HasForeignKey("AdvocateId");

                    b.HasOne("Tigerspike.Solv.Domain.Models.Ticket", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.TicketTag", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.Ticket", null)
                        .WithMany("Tags")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tigerspike.Solv.Domain.Models.WebHook", b =>
                {
                    b.HasOne("Tigerspike.Solv.Domain.Models.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tigerspike.Solv.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
