SET FOREIGN_KEY_CHECKS = 0;

ALTER DATABASE solv CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE solv.__efmigrationshistory CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.abandonreason CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocate CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocateapplication CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocateapplicationbrand CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocateblockhistory CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocatebrand CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocateinvoice CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocateinvoicelineitem CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocatequizanswer CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocatequizattempt CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.apikey CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.billingdetails CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.brand CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.brandadvocateresponseconfig CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.brandformfield CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.brandformfieldtype CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.brandnotificationconfig CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.brandticketpricehistory CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.category CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.chataction CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.chatactionoption CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.chatsideeffect CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.client CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.clientinvoice CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.inductionadvocatesectionitem CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.inductionsection CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.inductionsectionitem CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.invoicingcycle CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.payment CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.paymentroute CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.probingform CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.probingquestion CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.probingquestionoption CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.probingresult CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profileanswer CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profileapplicationanswer CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profilearea CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profilebrands CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profilequestion CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profilequestiondependency CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profilequestionoption CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profilequestionoptiondependency CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profilequestiontype CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_blob_triggers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_calendars CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_cron_triggers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_fired_triggers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_job_details CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_locks CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_paused_trigger_grps CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_scheduler_state CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_simple_triggers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_simprop_triggers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_triggers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.quiz CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.quizquestion CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.quizquestionoption CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.rejectionreason CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.sequence CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.tag CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticket CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketabandonhistory CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketabandonreason CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketcategory CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketescalationconfig CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketimport CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketimportfailure CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketimporttag CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketmetadataitem CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketrejectionhistory CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketrejectionreason CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketsource CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketstatushistory CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.tickettag CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.trackingdetail CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.webhook CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.abandonreason CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Name` `Name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocate CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `PaymentAccountId` `PaymentAccountId` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `CountryCode` `CountryCode` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Source` `Source` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `IdentityApplicantId` `IdentityApplicantId` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `IdentityCheckId` `IdentityCheckId` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `IdentityCheckResultUrl` `IdentityCheckResultUrl` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocateapplication CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Country` `Country` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Email` `Email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `DeletionHash` `DeletionHash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `State` `State` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Token` `Token` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `FirstName` `FirstName` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `LastName` `LastName` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Phone` `Phone` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Source` `Source` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocateapplicationbrand CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AdvocateApplicationId` `AdvocateApplicationId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocateblockhistory CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AdvocateId` `AdvocateId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocatebrand CHANGE `AdvocateId` `AdvocateId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocateinvoice CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AdvocateId` `AdvocateId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `InvoicingCycleId` `InvoicingCycleId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ReferenceNumber` `ReferenceNumber` varchar(95) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `PlatformBillingDetailsId` `PlatformBillingDetailsId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocateinvoicelineitem CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AdvocateInvoiceId` `AdvocateInvoiceId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocatequizanswer CHANGE `QuizAdvocateAttemptId` `QuizAdvocateAttemptId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `QuizQuestionOptionId` `QuizQuestionOptionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.advocatequizattempt CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AdvocateId` `AdvocateId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `QuizId` `QuizId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.apikey CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Key` `Key` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `UserId` `UserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ApplicationId` `ApplicationId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.billingdetails CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Name` `Name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Email` `Email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `VatNumber` `VatNumber` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `CompanyNumber` `CompanyNumber` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Address` `Address` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.brand CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Name` `Name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Thumbnail` `Thumbnail` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Logo` `Logo` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `PaymentAccountId` `PaymentAccountId` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BillingAgreementToken` `BillingAgreementToken` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BillingAgreementId` `BillingAgreementId` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BillingDetailsId` `BillingDetailsId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `InductionDoneMessage` `InductionDoneMessage` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `InductionInstructions` `InductionInstructions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.brandadvocateresponseconfig CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Content` `Content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ChatActionId` `ChatActionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `RelevantTo` `RelevantTo` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.brandformfield CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Name` `Name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Title` `Title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Validation` `Validation` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `DefaultValue` `DefaultValue` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Options` `Options` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Description` `Description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.brandformfieldtype CHANGE `Name` `Name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.brandnotificationconfig CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Subject` `Subject` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Header` `Header` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Body` `Body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.brandticketpricehistory CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `UserId` `UserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.category CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Name` `Name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.chataction CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.chatactionoption CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ChatActionId` `ChatActionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Label` `Label` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Value` `Value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.chatsideeffect CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ChatActionOptionId` `ChatActionOptionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Value` `Value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.client CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.clientinvoice CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ReferenceNumber` `ReferenceNumber` varchar(95) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `InvoicingCycleId` `InvoicingCycleId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandBillingDetailsId` `BrandBillingDetailsId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `PlatformBillingDetailsId` `PlatformBillingDetailsId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.inductionadvocatesectionitem CHANGE `SectionItemId` `SectionItemId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AdvocateId` `AdvocateId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.inductionsection CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Name` `Name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.inductionsectionitem CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Name` `Name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Source` `Source` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `SectionId` `SectionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.invoicingcycle CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.payment CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ReferenceNumber` `ReferenceNumber` varchar(95) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ClientInvoiceId` `ClientInvoiceId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AdvocateInvoiceLineItemId` `AdvocateInvoiceLineItemId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.paymentroute CHANGE `Name` `Name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.probingform CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Title` `Title` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.probingquestion CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ProbingFormId` `ProbingFormId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Text` `Text` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Code` `Code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Description` `Description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.probingquestionoption CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `QuestionId` `QuestionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Text` `Text` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Value` `Value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.probingresult CHANGE `TicketId` `TicketId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ProbingQuestionId` `ProbingQuestionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ProbingQuestionOptionId` `ProbingQuestionOptionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profileanswer CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ApplicationAnswerId` `ApplicationAnswerId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `QuestionOptionId` `QuestionOptionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `StaticAnswer` `StaticAnswer` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profileapplicationanswer CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AdvocateApplicationId` `AdvocateApplicationId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `QuestionId` `QuestionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profilearea CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Title` `Title` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profilebrands CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandName` `BrandName` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profilequestion CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AreaId` `AreaId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `QuestionTypeId` `QuestionTypeId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Title` `Title` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `SubTitle` `SubTitle` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profilequestiondependency CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `QuestionOptionId` `QuestionOptionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `QuestionId` `QuestionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profilequestionoption CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `QuestionId` `QuestionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Text` `Text` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `SubText` `SubText` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profilequestionoptiondependency CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `QuestionOptionId` `QuestionOptionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `QuestionOptionDependencyTargetId` `QuestionOptionDependencyTargetId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.profilequestiontype CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Name` `Name` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_blob_triggers CHANGE `SCHED_NAME` `SCHED_NAME` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_NAME` `TRIGGER_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_GROUP` `TRIGGER_GROUP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_calendars CHANGE `SCHED_NAME` `SCHED_NAME` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `CALENDAR_NAME` `CALENDAR_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_cron_triggers CHANGE `SCHED_NAME` `SCHED_NAME` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_NAME` `TRIGGER_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_GROUP` `TRIGGER_GROUP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `CRON_EXPRESSION` `CRON_EXPRESSION` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TIME_ZONE_ID` `TIME_ZONE_ID` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_fired_triggers CHANGE `SCHED_NAME` `SCHED_NAME` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ENTRY_ID` `ENTRY_ID` varchar(140) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_NAME` `TRIGGER_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_GROUP` `TRIGGER_GROUP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `INSTANCE_NAME` `INSTANCE_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `STATE` `STATE` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `JOB_NAME` `JOB_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `JOB_GROUP` `JOB_GROUP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_job_details CHANGE `SCHED_NAME` `SCHED_NAME` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `JOB_NAME` `JOB_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `JOB_GROUP` `JOB_GROUP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `DESCRIPTION` `DESCRIPTION` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `JOB_CLASS_NAME` `JOB_CLASS_NAME` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_locks CHANGE `SCHED_NAME` `SCHED_NAME` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `LOCK_NAME` `LOCK_NAME` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_paused_trigger_grps CHANGE `SCHED_NAME` `SCHED_NAME` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_GROUP` `TRIGGER_GROUP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_scheduler_state CHANGE `SCHED_NAME` `SCHED_NAME` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `INSTANCE_NAME` `INSTANCE_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_simple_triggers CHANGE `SCHED_NAME` `SCHED_NAME` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_NAME` `TRIGGER_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_GROUP` `TRIGGER_GROUP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_simprop_triggers CHANGE `SCHED_NAME` `SCHED_NAME` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_NAME` `TRIGGER_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_GROUP` `TRIGGER_GROUP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `STR_PROP_1` `STR_PROP_1` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `STR_PROP_2` `STR_PROP_2` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `STR_PROP_3` `STR_PROP_3` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TIME_ZONE_ID` `TIME_ZONE_ID` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.qrtz_triggers CHANGE `SCHED_NAME` `SCHED_NAME` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_NAME` `TRIGGER_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_GROUP` `TRIGGER_GROUP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `JOB_NAME` `JOB_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `JOB_GROUP` `JOB_GROUP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `DESCRIPTION` `DESCRIPTION` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_STATE` `TRIGGER_STATE` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TRIGGER_TYPE` `TRIGGER_TYPE` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `CALENDAR_NAME` `CALENDAR_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.quiz CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Title` `Title` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Description` `Description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `FailureMessage` `FailureMessage` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `SuccessMessage` `SuccessMessage` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.quizquestion CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `QuizId` `QuizId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Title` `Title` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.quizquestionoption CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `QuestionId` `QuestionId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Text` `Text` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.rejectionreason CHANGE `Name` `Name` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.sequence CHANGE `Name` `Name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.tag CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Name` `Name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ParentTagId` `ParentTagId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Description` `Description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticket CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Question` `Question` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AdvocateId` `AdvocateId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `CustomerId` `CustomerId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ClientInvoiceId` `ClientInvoiceId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AdvocateInvoiceId` `AdvocateInvoiceId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ReferenceId` `ReferenceId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `EscalatedById` `EscalatedById` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `SposDetails` `SposDetails` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `FraudRisks` `FraudRisks` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketabandonhistory CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TicketId` `TicketId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AdvocateId` `AdvocateId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketabandonreason CHANGE `TicketAbandonHistoryId` `TicketAbandonHistoryId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AbandonReasonId` `AbandonReasonId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketcategory CHANGE `TicketId` `TicketId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `CategoryId` `CategoryId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `UserId` `UserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketescalationconfig CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `CustomerMessage` `CustomerMessage` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketimport CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `FileName` `FileName` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `UserId` `UserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketimportfailure CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TicketImportId` `TicketImportId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `RawInput` `RawInput` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `FailureReason` `FailureReason` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketimporttag CHANGE `TicketImportId` `TicketImportId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TagId` `TagId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketmetadataitem CHANGE `TicketId` `TicketId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Key` `Key` varchar(95) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Value` `Value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandFormFieldId` `BrandFormFieldId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketrejectionhistory CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TicketId` `TicketId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketrejectionreason CHANGE `TicketRejectionHistoryId` `TicketRejectionHistoryId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketsource CHANGE `Name` `Name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.ticketstatushistory CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TicketId` `TicketId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AdvocateId` `AdvocateId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.tickettag CHANGE `TicketId` `TicketId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TagId` `TagId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `UserId` `UserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.trackingdetail CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `UserId` `UserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `TicketId` `TicketId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `IpAddress` `IpAddress` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `UserAgent` `UserAgent` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Event` `Event` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.user CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `FirstName` `FirstName` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `LastName` `LastName` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Email` `Email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Phone` `Phone` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `AlternateEmail` `AlternateEmail` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Country` `Country` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `State` `State` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.webhook CHANGE `Id` `Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `BrandId` `BrandId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `UserId` `UserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Url` `Url` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Secret` `Secret` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Authorization` `Authorization` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Body` `Body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ContentType` `ContentType` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `Verb` `Verb` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE solv.__efmigrationshistory CHANGE `MigrationId` `MigrationId` varchar(95) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, CHANGE `ProductVersion` `ProductVersion` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;


REPAIR TABLE solv.__efmigrationshistory;
REPAIR TABLE solv.abandonreason;
REPAIR TABLE solv.advocate;
REPAIR TABLE solv.advocateapplication;
REPAIR TABLE solv.advocateapplicationbrand;
REPAIR TABLE solv.advocateblockhistory;
REPAIR TABLE solv.advocatebrand;
REPAIR TABLE solv.advocateinvoice;
REPAIR TABLE solv.advocateinvoicelineitem;
REPAIR TABLE solv.advocatequizanswer;
REPAIR TABLE solv.advocatequizattempt;
REPAIR TABLE solv.apikey;
REPAIR TABLE solv.billingdetails;
REPAIR TABLE solv.brand;
REPAIR TABLE solv.brandadvocateresponseconfig;
REPAIR TABLE solv.brandformfield;
REPAIR TABLE solv.brandformfieldtype;
REPAIR TABLE solv.brandnotificationconfig;
REPAIR TABLE solv.brandticketpricehistory;
REPAIR TABLE solv.category;
REPAIR TABLE solv.chataction;
REPAIR TABLE solv.chatactionoption;
REPAIR TABLE solv.chatsideeffect;
REPAIR TABLE solv.client;
REPAIR TABLE solv.clientinvoice;
REPAIR TABLE solv.inductionadvocatesectionitem;
REPAIR TABLE solv.inductionsection;
REPAIR TABLE solv.inductionsectionitem;
REPAIR TABLE solv.invoicingcycle;
REPAIR TABLE solv.payment;
REPAIR TABLE solv.paymentroute;
REPAIR TABLE solv.probingform;
REPAIR TABLE solv.probingquestion;
REPAIR TABLE solv.probingquestionoption;
REPAIR TABLE solv.probingresult;
REPAIR TABLE solv.profileanswer;
REPAIR TABLE solv.profileapplicationanswer;
REPAIR TABLE solv.profilearea;
REPAIR TABLE solv.profilebrands;
REPAIR TABLE solv.profilequestion;
REPAIR TABLE solv.profilequestiondependency;
REPAIR TABLE solv.profilequestionoption;
REPAIR TABLE solv.profilequestionoptiondependency;
REPAIR TABLE solv.profilequestiontype;
REPAIR TABLE solv.qrtz_blob_triggers;
REPAIR TABLE solv.qrtz_calendars;
REPAIR TABLE solv.qrtz_cron_triggers;
REPAIR TABLE solv.qrtz_fired_triggers;
REPAIR TABLE solv.qrtz_job_details;
REPAIR TABLE solv.qrtz_locks;
REPAIR TABLE solv.qrtz_paused_trigger_grps;
REPAIR TABLE solv.qrtz_scheduler_state;
REPAIR TABLE solv.qrtz_simple_triggers;
REPAIR TABLE solv.qrtz_simprop_triggers;
REPAIR TABLE solv.qrtz_triggers;
REPAIR TABLE solv.quiz;
REPAIR TABLE solv.quizquestion;
REPAIR TABLE solv.quizquestionoption;
REPAIR TABLE solv.rejectionreason;
REPAIR TABLE solv.sequence;
REPAIR TABLE solv.tag;
REPAIR TABLE solv.ticket;
REPAIR TABLE solv.ticketabandonhistory;
REPAIR TABLE solv.ticketabandonreason;
REPAIR TABLE solv.ticketcategory;
REPAIR TABLE solv.ticketescalationconfig;
REPAIR TABLE solv.ticketimport;
REPAIR TABLE solv.ticketimportfailure;
REPAIR TABLE solv.ticketimporttag;
REPAIR TABLE solv.ticketmetadataitem;
REPAIR TABLE solv.ticketrejectionhistory;
REPAIR TABLE solv.ticketrejectionreason;
REPAIR TABLE solv.ticketsource;
REPAIR TABLE solv.ticketstatushistory;
REPAIR TABLE solv.tickettag;
REPAIR TABLE solv.trackingdetail;
REPAIR TABLE solv.user;
REPAIR TABLE solv.webhook;
OPTIMIZE TABLE solv.__efmigrationshistory;
OPTIMIZE TABLE solv.abandonreason;
OPTIMIZE TABLE solv.advocate;
OPTIMIZE TABLE solv.advocateapplication;
OPTIMIZE TABLE solv.advocateapplicationbrand;
OPTIMIZE TABLE solv.advocateblockhistory;
OPTIMIZE TABLE solv.advocatebrand;
OPTIMIZE TABLE solv.advocateinvoice;
OPTIMIZE TABLE solv.advocateinvoicelineitem;
OPTIMIZE TABLE solv.advocatequizanswer;
OPTIMIZE TABLE solv.advocatequizattempt;
OPTIMIZE TABLE solv.apikey;
OPTIMIZE TABLE solv.billingdetails;
OPTIMIZE TABLE solv.brand;
OPTIMIZE TABLE solv.brandadvocateresponseconfig;
OPTIMIZE TABLE solv.brandformfield;
OPTIMIZE TABLE solv.brandformfieldtype;
OPTIMIZE TABLE solv.brandnotificationconfig;
OPTIMIZE TABLE solv.brandticketpricehistory;
OPTIMIZE TABLE solv.category;
OPTIMIZE TABLE solv.chataction;
OPTIMIZE TABLE solv.chatactionoption;
OPTIMIZE TABLE solv.chatsideeffect;
OPTIMIZE TABLE solv.client;
OPTIMIZE TABLE solv.clientinvoice;
OPTIMIZE TABLE solv.inductionadvocatesectionitem;
OPTIMIZE TABLE solv.inductionsection;
OPTIMIZE TABLE solv.inductionsectionitem;
OPTIMIZE TABLE solv.invoicingcycle;
OPTIMIZE TABLE solv.payment;
OPTIMIZE TABLE solv.paymentroute;
OPTIMIZE TABLE solv.probingform;
OPTIMIZE TABLE solv.probingquestion;
OPTIMIZE TABLE solv.probingquestionoption;
OPTIMIZE TABLE solv.probingresult;
OPTIMIZE TABLE solv.profileanswer;
OPTIMIZE TABLE solv.profileapplicationanswer;
OPTIMIZE TABLE solv.profilearea;
OPTIMIZE TABLE solv.profilebrands;
OPTIMIZE TABLE solv.profilequestion;
OPTIMIZE TABLE solv.profilequestiondependency;
OPTIMIZE TABLE solv.profilequestionoption;
OPTIMIZE TABLE solv.profilequestionoptiondependency;
OPTIMIZE TABLE solv.profilequestiontype;
OPTIMIZE TABLE solv.qrtz_blob_triggers;
OPTIMIZE TABLE solv.qrtz_calendars;
OPTIMIZE TABLE solv.qrtz_cron_triggers;
OPTIMIZE TABLE solv.qrtz_fired_triggers;
OPTIMIZE TABLE solv.qrtz_job_details;
OPTIMIZE TABLE solv.qrtz_locks;
OPTIMIZE TABLE solv.qrtz_paused_trigger_grps;
OPTIMIZE TABLE solv.qrtz_scheduler_state;
OPTIMIZE TABLE solv.qrtz_simple_triggers;
OPTIMIZE TABLE solv.qrtz_simprop_triggers;
OPTIMIZE TABLE solv.qrtz_triggers;
OPTIMIZE TABLE solv.quiz;
OPTIMIZE TABLE solv.quizquestion;
OPTIMIZE TABLE solv.quizquestionoption;
OPTIMIZE TABLE solv.rejectionreason;
OPTIMIZE TABLE solv.sequence;
OPTIMIZE TABLE solv.tag;
OPTIMIZE TABLE solv.ticket;
OPTIMIZE TABLE solv.ticketabandonhistory;
OPTIMIZE TABLE solv.ticketabandonreason;
OPTIMIZE TABLE solv.ticketcategory;
OPTIMIZE TABLE solv.ticketescalationconfig;
OPTIMIZE TABLE solv.ticketimport;
OPTIMIZE TABLE solv.ticketimportfailure;
OPTIMIZE TABLE solv.ticketimporttag;
OPTIMIZE TABLE solv.ticketmetadataitem;
OPTIMIZE TABLE solv.ticketrejectionhistory;
OPTIMIZE TABLE solv.ticketrejectionreason;
OPTIMIZE TABLE solv.ticketsource;
OPTIMIZE TABLE solv.ticketstatushistory;
OPTIMIZE TABLE solv.tickettag;
OPTIMIZE TABLE solv.trackingdetail;
OPTIMIZE TABLE solv.user;
OPTIMIZE TABLE solv.webhook;